### ISSUE TITLE
Cockpit Widgets and Skins

### ISSUE THREAD

**Issue by estackpole** [OpenROV/openrov-software#123]
Gauges, displays, and themes used in Cockpit should be changeable.    Using a program that is as user-friendly as possible, people in the OpenROV community should be able to design their own interface appearances which could be shared and used by others in the community.   This way, Cockpit appearances could be customized by users if so desired around the core structure of Cockpit's functionality.

**Comment by BrianAdams** [comment]
Implemented in #341
