### ISSUE TITLE
Refactor: Motor Diag code should be cleaned up

### ISSUE THREAD

**Issue by codewithpassion** [OpenROV/openrov-software#266]
As my comment on commit 6b3c1d5 shows, the ```listen()``` function should be refactored.

### Things to cleanup
* click handlers should be done via data binding, not using jquery to be consistent with the use of KO
* The subscribing on model knockout event's should not happen in the ```listen()``` function as this function is there to listen to things from the cockpit or other plugins. The ```listen()``` function is called from the Cockpit itself when the plugins are loaded
* The callback passed to the ```load()``` funciton when the diag panel is loaded should point to the new function that does the subscription and ```ko.applyBindings()```

**Comment by BrianAdams** [comment]
@codewithpassion can you confirm the latest refactor took care of this?

**Comment by codewithpassion** [comment]
Yes
