### ISSUE TITLE
The istallation of community issues doesn't seem to work

### ISSUE THREAD

**Issue by codewithpassion** [OpenROV/openrov-software#306]
The 'progress bar' doesn't go away and in the log file I found this:

{ [Error: Failed to execute "git ls-remote --tags --heads https://github.com/BrianAdams/openrov-plugin-divealerts.git", exit code of #128]
  code: 'ECMDERR',
  details: 'error: The requested URL returned error: 403 while accessing https://github.com/BrianAdams/openrov-plugin-divealerts.git/info/refs\nfatal: HTTP request failed\n',
  exitCode: 128,
  data: 
   { endpoint: 
      { name: 'openrov-plugin-divealerts',
        source: 'openrov-plugin-divealerts',
        target: '*' },
     resolver: 
      { name: 'openrov-plugin-divealerts',
        source: 'https://github.com/BrianAdams/openrov-plugin-divealerts.git',
        target: '*' },
     canonicalDir: '/root/.cache/bower/packages/cc4b38257bcb2edc566a345be77ef40b/0.0.3',
     pkgMeta: 
      { name: 'openrov-plugin-divealerts',
        description: 'real-time alerts based on telemetry data analysis',
        version: '0.0.3',
        homepage: 'https://github.com/BrianAdams/openrov-plugin-divealerts',
        main: 'public/js/divealerts.js',
        keywords: [Object],
        dependencies: [Object],
        _release: '0.0.3',
        _resolution: [Object],
        _source: 'https://github.com/BrianAdams/openrov-plugin-divealerts.git',
        _target: '*' } } }

**Comment by BrianAdams** [comment]
Tested and verified in 30.0.3
