### ISSUE TITLE
UI needs to allow for adjustment of motor bias

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#325]
Most motors have non-linear behavior. There is a hardcoded bias in the code today so that multiplies the thruster with a bias value to try and make it linear.  That needs to be use changeable in the case the ROV won't fly straight.

**Comment by WaltHolm** [comment]
Seems like this should be part of the ucontroller refactor by @spiderkeys, or else closed and dropped.

**Comment by spiderkeys** [comment]
Part of my controls rework involves adding an interface for loading non-linear motor thrust profiles, which should hopefully improve our ability to generate symmetrical thrust. Once RPM feedback is available, we can combine the thrust profile with a controller that tracks a target RPM to improve on that even more.

**Comment by BrianAdams** [comment]
That hard coded biases are now exposed in settings.

**Comment by depperson** [comment]
Is it in v30.0.3?

**Comment by BrianAdams** [comment]
The UI in settings is currently in the Master branch, so it will be part of
the next stable release.

**Comment by depperson** [comment]
Did this make it into a release yet?
