### ISSUE TITLE
Proxy stop fails [30.0.0 Pre-release build 152]

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#343]
rov@OpenROV:~$ sudo /etc/init.d/openrov-proxy stop
[sudo] password for rov:
/opt/openrov/proxy//app.js
[....] Stopping OpenROV NodeJS proxy server: openrov-proxy[....]   --->  OpenROV NodeJS proxy server stopped: openrov-proxyfatal: bad config file line 1 in /etc/gitconfig
fatal: bad config file line 1 in /etc/gitconfig
fatal: bad config file line 1 in /etc/gitconfig

**Comment by BrianAdams** [comment]
Not appearing in latest dev image. Closing for now.

**Comment by saulibanez** [comment]
good afternoon,
I have the same problem with the proxy, is there a solution?

rov@OpenROV:~$ sudo /etc/init.d/openrov-proxy stop
[sudo] password for rov: 
/opt/openrov/proxy//app.js
[....] Stopping OpenROV NodeJS proxy server: openrov-proxy[....]   --->  OpenROV NodeJS proxy server stopped: openrov-proxyfatal: bad config file line 1 in /etc/gitconfig
fatal: bad config file line 1 in /etc/gitconfig
fatal: bad config file line 1 in /etc/gitconfig
. ok 

Regards
