### ISSUE TITLE
Reintroduce SAMPLE_PERIOD concept to rovpilot.js on the browser side

### ISSUE THREAD

**Issue by codewithpassion** [OpenROV/openrov-software#346]
https://github.com/OpenROV/openrov-software/blob/master/src/plugins/rovpilot/public/js/rovpilot.js#L6

SAMPLE_PERIOD used to be used to limit the rate at which commands are sent to the ROV.

Check the comment on the PR:
https://github.com/OpenROV/openrov-software/pull/341#discussion_r26783640

**Comment by BrianAdams** [comment]
This has been added back in master
