### ISSUE TITLE
Photos should have the correct timestamp

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#372]
The current system uses the time from the beaglebone which is reset after power cycles.  The system should somehow get the time from the host computer and use that as the timestamp.  This is to make it easier to properly group the photos captured on different dives.

**Comment by codewithpassion** [comment]
We could just set the ROV time from the browser on connection.

**Comment by BrianAdams** [comment]
Time on the bbb is now set by the browser.
