### ISSUE TITLE
NewUI Refactor: Telemetry screen no longer allows scrolling

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#393]
The system used to let you scroll down to see additional telemetry if it fills the screen

**Comment by codewithpassion** [comment]
I still get the scrollbar 
![image](https://cloud.githubusercontent.com/assets/1607486/7462536/1790ced0-f267-11e4-9f78-2b5300d21ecb.png)

**Comment by BrianAdams** [comment]
Confirmed we are seeing this as an issue on OS/X + Chrome

**Comment by covedesign** [comment]
I have the same problem with scrolling in OSX + Chrome

**Comment by jacobrosenthal** [comment]
These scroll for me as of 65205a8
OSX 10.10.3 (14D136)
43.0.2357.124 (64-bit)

Can we get some versions?

**Comment by BrianAdams** [comment]
One of the issues is that the size of the area is about 30px or so longer than shown. The footer covers the bottom part.  If there is not enough data to actually overflow the element the scrollbar won't show.  Even if you do scroll, you cannot get to the bottom covered by the footer.

**Comment by BrianAdams** [comment]
This area was moved out of the new-ui cockpit.  The classic cockpit is being dialed in.  If it is still an issue in cockpit after the refactor we will reopen.
