### ISSUE TITLE
NewUI Refactor: Keyboard commands are missing from the keyboard icon overlay

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#409]
Under keyboard commands should be a list of all of the keyboard commands.  It is now blank.
![openrov_cockpit](https://cloud.githubusercontent.com/assets/1471826/7602956/48a2e902-f8e0-11e4-9726-8a5d1b631f84.png)

**Comment by jacobrosenthal** [comment]
The div they were relying on was removed in this commit. 
https://github.com/OpenROV/openrov-software/commit/62e7fb792658e1975bf4b4dac7055c0d72099fb8#diff-cde871289a380b2947f4e6d85a019df8L121

**Comment by BrianAdams** [comment]
Keyboard commands are now an applet that can be navigated to in 31.1
