### ISSUE TITLE
UI Refactor: Cannot select items with the keyboard from the heads up menu.

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#412]
After pressing the 'e' button I see the menu.  I appear to have no way to select anything and the arrow keys don't seem to do anything.  Releasing 'e' and the menu disappears.
![openrov_cockpit](https://cloud.githubusercontent.com/assets/1471826/7603114/7ad20b18-f8e2-11e4-89be-2475a71dcc06.png)

**Comment by codewithpassion** [comment]
As the Arrow keys are used for motor controls, the heads up menu can't bind to them easily.
The keys are:
c: move down
d: move up
t: move right (with aux servo plugin)
r: move left ('')

**Comment by BrianAdams** [comment]
Thanks. Validated.
