### ISSUE TITLE
UI Refactor: The presets for the Lithium Iron batteries has dissapeared

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#413]
These were added with #311.

![openrov_cockpit](https://cloud.githubusercontent.com/assets/1471826/7603187/be5a43d6-f8e3-11e4-9df1-c9942fb4531a.png)

**Comment by codewithpassion** [comment]
the configuration is there: https://github.com/OpenROV/openrov-cockpit/blob/master/src/plugins/capestatus/index.js#L158
check that you don't have an old rovconfig.json on the ROV you tested this.
