### ISSUE TITLE
nginx service fails to start

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#434]
The service which is managed via SystemD is supposed to start up after the service that creates the log directory in the \var\log folder (which is in ram and deleted every time we power off).  For whatever reason, the service attempts to start before the nginx log folder has been created.

**Comment by codewithpassion** [comment]
Fixed the problem on my BB by changing a line in ```/etc/init.d/nginx```

         # Required-Start:    $local_fs $remote_fs $network $syslog $named $prepare_dirs

adding the ***$prepare_dirs*** at the end
