### ISSUE TITLE
Compas ticker partially covered in master

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#443]
![openrov_cockpit_and_node_inspector_-_file____users_brian_openrov-cockpit_src_cockpit_js_and_1__rov_openrov_____node_](https://cloud.githubusercontent.com/assets/1471826/9159948/30a0230e-3ee7-11e5-907d-7e7cca913e10.jpg)

**Comment by BrianAdams** [comment]
Ticker has been removed

**Comment by codewithpassion** [comment]
Well, that's a solution.
But not sure if it's the right one.
