### ISSUE TITLE
30.0.3 pre-release samba cannot connect 

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#462]
Using OS/X

The systemd made them make changes to the samba system.  The smbd and nmbd services are now separately managed.  The single samba wrapper no longer works.

Tried connecting with the default config and with the old config that we used before.

The system also starts the active directory integrated auth by default now. Not sure if that is a factor.

The system also does not create logs unless you manually create the /var/log/samba folder.

**Comment by BrianAdams** [comment]
@codewithpassion 
Here are the steps I have run through
Login to the image
append the following to /etc/samba/smb.conf
```
[OpenROV]
comment = OpenROV Cockpit
path = /
force user = rov
force group = admin
read only = No
guest ok = Yes
```

execute: `sudo systemctl restart smbd nmbd`
I check and it appears to create the \var\log\samba folder

When attempting to connect from OS/X I always get a connectivity error

**Comment by BrianAdams** [comment]
@spiderkeys can you try connecting to the 30.0.3 image using your windows box via file share \\192.168.254.1\OpenROV

**Comment by spiderkeys** [comment]
No bueno.

**Comment by BrianAdams** [comment]
Passed QA for 30.0.3 for connecting via guest.  Still something wonky connecting with credentials. Moving to next release.

**Comment by BrianAdams** [comment]
Have removed Samba as a feature.
