### ISSUE TITLE
Tab complete doesn't always work for apt-get in 30.0.3

### ISSUE THREAD

**Issue by spiderkeys** [OpenROV/openrov-software#469]
Main failure is that you can't tab complete apt-get installs. I feel like I've seen it fail in other cases as well, but can't recall or reproduce them at the moment. Filesystem tab completes seem to work fine.

**Comment by BrianAdams** [comment]
Could it be that apt-get needed an update before it could complete?

**Comment by BrianAdams** [comment]
This is not a priority. If you want to work on it, by all means.
