### ISSUE TITLE
30.0.3 Changing motor directions does not consistently reconfigure the motor

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#473]
When initially switching the direction of the starboard thruster and vertical thruster, I noticed that the starboard thruster was switched correctly, but the vertical thruster ended up moving the same direction for both shift and control commands.  If I opened and closed the diagnostics window a second time (without changing any values) the problem was fixed and the motor direction worked correctly.

**Comment by BrianAdams** [comment]
The system makes several calls back to the ROV to reset its motor configuration.  If one of those calls fails (serial corruption), that could explain the above behavior.  Opening and closing the diagnostics windows resends the configuration back to the motors.

**Comment by briangrau** [comment]
Noted in https://openrov.ontestpad.com/script/7/#81/7/

**Comment by BrianAdams** [comment]
This has been fixed.
