### ISSUE TITLE
Arduino Firmware runs on the ARM M0+ SAMD21J18A

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#486]
This feature allows the ROV firmware to run on the ARM M0+ chipset and ATMega2560 chipset using the same firmware sketch.
### Key tasks
- [x] Create a build system that can compile the same source firmware for SAMD21.
- [x] Create image flashing system that supports flashing to the SAMD21 from the beaglebone.
- [x] Port the Arduino code to the SAMD21 chipset.
- [x] Create automated build scripts for build environment.
- [ ] Create unit tests over key functionality that pass to ensure refactoring did not change behavior.
### Validation criteria
- [ ] Unit tests reviewed with @brianadams
- [ ] All unit tests pass
- [ ] ROV with firmware passes manual verification with production team

**Comment by spiderkeys** [comment]
Moved away from Arduino framework for the SAMD21. Application has been ported to RIOT OS.
