### ISSUE TITLE
NGINX config for SSL

### ISSUE THREAD

**Issue by codewithpassion** [OpenROV/openrov-software#511]
I had to add 

ssl_ciphers AESGCM:HIGH:!aNULL:!MD5;

to the NGinx config on the last dev image.
Chrome version 50.0.2661.102

See http://garthkerr.com/transport-security-for-http2-protocol-with-nginx/

**Comment by BrianAdams** [comment]
Apparently still an issue on Linux+Chrome

**Comment by BrianAdams** [comment]
Fixes in platform branches
