### ISSUE TITLE
Lights Need to Be Scaled to Be Linear

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#519]
31.0.1-PAL-02: The internal lights need to be scaled so they increment up in brightness in a linear fashion.

**Comment by briangrau** [comment]
Lookup table PWM values

48
64
96
160
255

**Comment by briangrau** [comment]
![img_1623](https://cloud.githubusercontent.com/assets/8497043/17576353/a3cf27e8-5f26-11e6-89f3-c8901f720d1d.JPG)

**Comment by spiderkeys** [comment]
Implemented.
