### ISSUE TITLE
External Lights Do Not Work

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#520]
31.0.1-PAL-02: The external lights do not work. When they are working, they also need to be scaled to be linear in brightness.

**Comment by spiderkeys** [comment]
I believe I have fixed this with the latest update to cockpit and firmware-2.0, but we will need to verify on a new image.

**Comment by spiderkeys** [comment]
https://github.com/OpenROV/openrov-cockpit/commit/f5939d9fbcbd7f96abddcfefee62a62aac2ba047
https://github.com/OpenROV/openrov-software-arduino/commit/91b8cdba6f1ca5fb56946475b1fd7b80d2c9caf7

**Comment by BrianAdams** [comment]
The mock returns elight0/elight1 not supported in mock

**Comment by spiderkeys** [comment]
Fixed. https://github.com/OpenROV/openrov-cockpit/commit/0931f01abb11c9092f237801f6208562c426616f
