### ISSUE TITLE
Cockpit Battery current/voltage widget not being updated properly

### ISSUE THREAD

**Issue by WaltHolm** [OpenROV/openrov-software#533]
Conditions:  31.0.1-dev-pal-04.  PC with Windows 7, Chrome 51.0.2704.103m.

When using the new (default) cockpit theme, the updating of the battery current/voltage widget is erratic, and sometimes doesn't update at all.  When switching into cockpit from another page, if the widget doesn't update at all, it displays 5V and 100ma, which can be a bit deceptive- perhaps the default values should be zeros instead (or dashes if a non-numeric character is allowed)?

On the telemetry and engineering pages, updating of current and voltage information seems OK.

**Comment by BrianAdams** [comment]
fixed in github.com/OpenROV/openrov-cockpit/pull/114
