### ISSUE TITLE
External light not working 

### ISSUE THREAD

**Issue by WaltHolm** [OpenROV/openrov-software#534]
Conditions:  31.0.1.dev-pal-04 PC with Windows7, Chrome 51.0.2704.103m.  OROV 2.8 with camera upgrade.

When working in the new cockpit, was not able to activate the external lights.  I tried both of the external light controls, and neither activated the lights.

**Comment by briangrau** [comment]
Needs testing

**Comment by BrianAdams** [comment]
should be fixed in latest build

**Comment by WaltHolm** [comment]
Tested in 31.0.1 Dev Pal 07 with Chrome 52.  Keypad now works, but mouse clicks to the XL indicators does not.

**Comment by WaltHolm** [comment]
Whoops, pressed the wrong button.  Re-opening issue.

**Comment by BrianAdams** [comment]
@spiderkeys said he knew off the top of his head what the issue was. Assigning to at least get the brain dump.

**Comment by spiderkeys** [comment]
Fixed in: https://github.com/OpenROV/openrov-cockpit/commit/30cad62c6033286980225f4d7581fadda49edaf8
