### ISSUE TITLE
Camera tilt doesn't work on gamepad

### ISSUE THREAD

**Issue by WaltHolm** [OpenROV/openrov-software#535]
Conditions:   31.0.1-dev-pal-04, PC with Windows7, Chrome 51.0.2704.103m, OROV 2.8 with camera upgrade, Logitech 310 gamepad.

Operation of the camera tilt stage works fine from the keypad, but does not work from the gamepad.

**Comment by BrianAdams** [comment]
This may have been an issue with the gamepad not being recognized correctly and the mappings being off.  Later attempts worked no problem.
