### ISSUE TITLE
Alignment and scroll issues in classic cockpit

### ISSUE THREAD

**Issue by WaltHolm** [OpenROV/openrov-software#537]
SW 31.0.1-dev-pal-04.  PC with Windows7, Chrome 51.0.2704.103m

When using the "classic" cockpit theme, the app menu has alignment issues (it's crushed way over on the right side of the screen), and the scroll bars don't work.  In the settings page the scroll bars don't work.  In the cockpit, the latency display has alignment problems.

**Comment by BrianAdams** [comment]
Theme has been removed until we have time to test the theme
