### ISSUE TITLE
Geo-video-server issues on initial install

### ISSUE THREAD

**Issue by WaltHolm** [OpenROV/openrov-software#541]
SW 31.0.1-dev-pal-04.  PC with Windows7, Chrome 51.0.2704.103m, OROV 2.8 with camera upgrade.

Noted by Charles Cross.

Upon the initial install of the software into an existing OROV 2.8, the Geo-video-server did not automatically detect a camera or the flash firmware.  Restarting orov-cockpit fixed this.  Subsequent power cycles of the ROV did not show this issue.

**Comment by spiderkeys** [comment]
I think this has been fixed. The new bug with first-boot has different symptoms.
