### ISSUE TITLE
Camera-tilt MCU api needs to be in float not micro-seconds

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#542]
Introduce a new API tiltp, that takes a float.   That float will be percent of a full rotation.  The limits that are in the firmware should be updated to accept the limits as set in the settings file for tilt.  Finally the tilt command should return immediately the new tilt-percent value every time it is adjusted.

Refer to the mock bridge.js code for the up to date API behavior.

https://github.com/OpenROV/openrov-software-arduino/blob/firmware-2.0/sketches/OpenROV2x/CCameraMount.cpp

**Comment by spiderkeys** [comment]
Addressed in API rework done here: https://github.com/OpenROV/openrov-cockpit/pull/131
