### ISSUE TITLE
Firmware does not build 

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#543]
I think this requires two changes
in buildfirmware and flashfirmware.js, change the sketch namefrom OpenROV to Trident
and fetch/checkout the branch i2c-work in /opt/openrov/arduino
then you should be good

**Comment by spiderkeys** [comment]
Fixed in https://github.com/OpenROV/openrov-cockpit/commit/c4314a72db00c79528630d62bc3320a59dcea9c5.

Merged i2c-work branch
