### ISSUE TITLE
Notes from Testing of DEV Build #169

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#559]
Overall the build is looking very good.

I like the remapping of the keyboard on the fly through cockpit :)

Here are notes for fixes:

- [x] sometimes when turning the lights on "i" key the lights just flicker and do not turn on (this might be tied to the computer since it is inconsistent) - Probably fixed as the light system was reworked

- [x] the "i" works to turn the lights on and off but the "o" and "p" keys do not work at all

- [x] in the keyboard applet there is no command to decrease the LEDs

- [x] when not in cockpit applet (e.g. data) still have control of the ROV...feature? bug? up for debate -Will not fix

- [x] It appears that there is a user default logged in? - will not fix

- [ ] One other note is that the first time I ran the ROV the video did not come up and had to do a restart of the ROV.

All tests done on lab computer.

Firmware upload through terminal worked.

**Comment by BrianAdams** [comment]
Opened a new issue tied to the video not starting the first time all the time
