### ISSUE TITLE
30.1.0 DEV #169 Lights do not always turn on when commanded

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#561]
From User:
3 out of 5 times the LEDs do not switch on properly. When I press 'i' on my keyboard it responds with a flash then goes off. Sometimes I manage to keep them on by holding down the 'i' key for a few seconds in which it responds with flash-flash-flash-flash-stays on. When it does turn on as it should, the LEDs come on at maximum power (which was fine), but when I begin to dim the light levels the 4 LEDs flicker in pairs unpredictably LED1 with LED2, LED3 with LED4 at the lower light levels. Sometimes the above doesn't happen at all (problem free) and I can't seem to figure out why it's so temperamental.

From Internal: I have seen this issue here in the lab as well.

**Comment by spiderkeys** [comment]
Fixed in https://github.com/OpenROV/openrov-cockpit/pull/136.

Will be official once merged.
