### ISSUE TITLE
30.1.0 DEV #169 When moving from Applet to Cockpit Chrome Dies

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#563]
From User:

Quite frequently when I want to go back to the cockpit from the configurator interface, the chrome page dies and needs to be reloaded. Is there a way to mitigate this issue?

From Internal: Nave not seen this issue...getting more info on computer and chrome specs.

**Comment by BrianAdams** [comment]
Not seeing on local hardware.  We are dialing in performance right now which may or may not help.  
Need browser/os/hardware details to do anything else.  Please re-open if we get those details.
