### ISSUE TITLE
The notification database access crashes

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#574]
Fatal cockpit crash when changing a keybinding. Can probably be triggered by other actions as well.

Steps to reproduce:
1. Run cockpit in mock mode in VScode
2. Open cockpit in browser
3. Open Input manager
4. Change a keybinding and click accept.
5. Immediately after clicking accept the following fatal error will occur:

![screenshot_20161018_142035](https://cloud.githubusercontent.com/assets/859469/19496859/5941d3b2-953e-11e6-9e06-15280e05550a.png)

Probably related to file permissions, as /tmp/ belongs to root:root by default on linux.

**Comment by BrianAdams** [comment]
Possible related issues:
Trying to open the database more than once: 
* https://github.com/louischatriot/nedb/issues/320
* https://github.com/louischatriot/nedb/issues/136

**Comment by nerdgilbert** [comment]
Verified on a fresh install. Made pull with master and restarted computer. Ran cockpit in debug mode and immediately threw this error. 
![notification_error](https://cloud.githubusercontent.com/assets/12476669/19497816/ee7e835e-9542-11e6-8276-e0f3f4bc84dc.png)

**Comment by BrianAdams** [comment]
Fix will go in soon. Workaround is in initdb (), in the promise try, check
if self.db exists, and return if it does.

**Comment by BrianAdams** [comment]
```
    initDB() {                   
        var self = this;
        return bluebird.try(function() {
            if (self.db){
                //Only initialize once, changes to settings used by nedb will requires a process restart.
                return;
            }
            if (process.env.NODE_ENV == "development") {
```
