### ISSUE TITLE
Geomux Hue Change Crashed Cockpit

### ISSUE THREAD

**Issue by briangrau** [OpenROV/openrov-software#576]
Note from a user.

Geomux hue: I was playing with various video settings during a dive, and I set hue to its minimum value of -18,000. My ROV effectively crashed; everything froze, and I was unable to reload the page. I had to power cycle the ROV to fix this. To be honest, I don’t even know what hue does, or what an acceptable value is for it. I haven’t touched it since.

**Comment by spiderkeys** [comment]
This and other untested parameter sliders have been removed from the UI until their effects are tested and any problems worked through.
