### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by simonech** [OpenROV/openrov-software#582]
When I launch the `npm run deploy:prod` command as specified in [Dev-HowTo](https://github.com/OpenROV/openrov-cockpit/blob/master/docs/DEV-HOWTO.md) I get the following error:

```
C:\Users\user\Documents\GitHub\openrov-cockpit>npm run deploy:prod

> OpenROV-Cockpit@31.0.0 deploy:prod C:\Users\user\Documents\GitHub\openrov-cockpit
> env 'npm_config_unsafe_perm=true' env 'npm_config_shrinkwrap=true' NODE_ENV=production npm install

'env' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by BrianAdams** [comment]
This was updated a couple days ago with windows instructions.

https://github.com/OpenROV/openrov-cockpit/commit/5d44c741b5bce7456e3d4d95777a2067fc5b1b01

Please re-open if it fails.
