### ISSUE TITLE
As user, when debugging, I want to see also the older log files, not just the latest so that I can see what happened before

### ISSUE THREAD

**Issue by simonech** [OpenROV/openrov-software#61]
Probably every time the openrov process is started via init.d start the latest log file should be renamed to log.0 log.1 log.2 log.3, etc

**Comment by BrianAdams** [comment]
This might be reasonable as a plugin.  The default system will flush the logs every power cycle. Part of this is to prevent the disk space from running out. The other reason is to limit the writes to physical media to help mitigate file corruption issues. Closing for now.
