### ISSUE TITLE
The system appears to be sending multiple commands on keyboard press

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#623]
For instance, the hitting light will toggle it off-on-off-on.

**Comment by BrianAdams** [comment]
Checked the input manager to ensure it was not somehow holding on to listeners. Registered several different presets, including the same one a couple time. In mock mode, sending a light command only happened once.

**Comment by nerdgilbert** [comment]
Was this reported on a vehicle?

**Comment by BrianAdams** [comment]
@nerdgilbert , yes. The test vehicle Grau was using.  If you can get a chance to take a look on vehicle, I think that is the next step.  Might be worth capturing the serial traffic while recreating the issue.

**Comment by BrianAdams** [comment]
@spiderkeys had a sense it might have to do with the syncTargetPower function that keeps retrying every 33ms until it gets a lights_tpow response from the MCU.  That it may be the round trip is taking too long and the message gets sent again. Now how a power off message would trigger a power on again is still a mystery.

**Comment by spiderkeys** [comment]
The command going to the firmware is a specific value. The only place the concept of toggling exists is the browser client, so delayed/repeated toggles are probably building up between the client and server. This behaviour has exhibited itself in many other commands as well, happening especially often on the BBB.

**Comment by BrianAdams** [comment]
This was tied to the gamepad press generating multiple gamepad click events. Opened other issues. Closing this one.
