### ISSUE TITLE
Tilt control target position adjust too quickly using the gamepad

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#624]
When using the gamepad to adjust up or down, the target position is moving so fast that you cannot really fine grain control the position of the tilt stage.
This was usinga  PS4 gamepad

**Comment by nerdgilbert** [comment]
Related to my comment here: https://github.com/OpenROV/openrov-software/issues/625#issuecomment-274222514

**Comment by BrianAdams** [comment]
Closing as Dupe of 625
