### ISSUE TITLE
Toggle controls on the gamepad should only fire on button release

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#625]
Currently if you hold down the button, it keeps toggling the lasers for instance.  It is too hard to get them off or on because it cycles too fast.

**Comment by nerdgilbert** [comment]
This is not reproducible in MOCK mode which makes me suspect that it is related to running using the hardware.

**Comment by BrianAdams** [comment]
Tried on hardware with the Logitech controller.  May be an odd behavior from the PS4 controller.

**Comment by nerdgilbert** [comment]
Fixed: https://github.com/OpenROV/openrov-cockpit/pull/197
